language: cpp


addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - mingw-w64

before_install:
  - pip install --user cpp-coveralls


script:
- cmake .
- make
- ./runUnitTests

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
